This update addresses a problem with conflicting declarations of "basic_string" which results in compiler errors like this:
   error: reference to 'basic_string' is ambiguous
   std::basic_string<char, std::char_traits<char>, std::allocator<char> > PUGIXML_FUNCTION as_utf8(const std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >& str);

This apparently only affects compilation done with GCC version 5.4.0 and
newer, including GCC 6.2.x.  This error was not observed on GCC 4.4.4 and GCC
5.3.0.

The patch associated with this update was provided by 'Hamlet' (circa 21 Dec
2016):

   http://forums.thedarkmod.com/topic/18570-my-experience-with-the-dark-mod-under-linux/#entry399077

The patch was provided with the following explanation:

   Use system string definition instead of making up one.

   It requires all the libraries (including the precompiled ones: read
   "Boost") to agree with the system definition though.

Additional testing of the patch under various environments is discussed here:

   http://forums.thedarkmod.com/topic/18543-compiling-tdm-204-under-linux/page-3#entry399418


git-svn-id: https://svn.thedarkmod.com/publicsvn/darkmod_src/trunk@6739 49c82d7f-2e2a-0410-a16f-ae8f201b507f